DROP TABLE IF EXISTS TRANSFER;
DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE TRANSFER (
    ACCOUNT_FROM VARCHAR,
    ACCOUNT_TO VARCHAR,
    MOUNT VARCHAR,
    STATUS VARCHAR
);

CREATE TABLE ACCOUNT (
    ACCOUNT_NUMBER VARCHAR,
    BALANCE VARCHAR
);

INSERT INTO TRANSFER VALUES ('ABC','XYZ','100','SUCCESS');
INSERT INTO TRANSFER VALUES ('XYZ','ABC','100','SUCCESS');
INSERT INTO ACCOUNT VALUES ('ABC','100');
INSERT INTO ACCOUNT VALUES ('XYZ','100');